name: duraspeed_checker
description: "A Flutter plugin for Android to detect the presence and status of DuraSpeed"
version: 0.0.1
homepage: https://github.com/ShayKisten/duraspeed_checker

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.duraspeed_checker
        pluginClass: DuraspeedCheckerPlugin
